
include: package:very_good_analysis/analysis_options.yaml
linter:

  rules:
    public_member_api_docs: false  
    use_key_in_widget_constructors: false     
    flutter_style_todos: false
    only_throw_errors: false
    use_build_context_synchronously: false

analyzer:
  exclude: 
    - '**/*.g.dart'
  plugins:
    - custom_lint